### ISSUE TITLE
Keeping keyboard open

### ISSUE THREAD

**Issue by mks-h** [aeri/Nihonoari-App#10]
Keyboard closes after submiting answer, and then opens again when kana changes. It is kinda annoying as it always flicker and you have to look at very bottom of screen to see correct answer. So I propose to keep keyboard open all the time.

**Comment by aeri** [comment]
Thank you for the suggestion, it is true that it can be annoying, I have been told about it on occasion. I have an idea to fix it in one of the future versions of the application. 

I hope it will be good, I will have to move the message over the keyboard and keep the keyboard static.

**Comment by aeri** [comment]
I published a [new release](https://github.com/aeri/Nihonoari-App/releases/tag/v1.4.0) where I've fixed this bug :)

**Comment by dpadar** [comment]
When it will be updated on f-droid?
