### ISSUE TITLE
Saving preferences

### ISSUE THREAD

**Issue by roxifas** [aeri/Nihonoari-App#13]
It would be really nice if the application would store the selected symbols between app restarts. For example: if I select hiragana, close the app and open it again, I would like to see hiragana already selected. Also, I would like to implement this feature, just as a personal challenge 🙂, if that's ok with you?

**Comment by aeri** [comment]
Thanks for the suggestion, I think it's a good idea especially if you're practicing a certain set for a while without having to adjust it every time. I'll try to make it the next app update.

**Comment by aeri** [comment]
I have linked a pull request that adds this functionality, once you click on accept, the selected set of kanas will be restored in the next session.

**Comment by roxifas** [comment]
Thank you for the PR! 🙂 I have written some comments on it, with how you can make the code a little bit better in my opinion.

**Comment by aeri** [comment]
Thanks for taking the time to review the code, I have applied all the changes you suggested.

By collaborating in this way we can all create a better application :)

**Comment by roxifas** [comment]
Very nice, I do have some more suggestions for this project, but they're more involved and I will leave them for another time and another issue 🙂

**Comment by aeri** [comment]
I published a new release with the feature, i expect that in a few days be available in F-Droid.
