### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by mks-h** [aeri/Nihonoari-App#18]
Translating answers based on ui language. Should support multiple answers, as there is different transliteration method for specific languages.

**Comment by mks-h** [comment]
I think, kana's table should show only one way of transliteration, while "correct answer is" can show different ways, as there are, most likely, no more then 4 of them.

**Comment by aeri** [comment]
I see that the standard and most widely used system for cyrillization into Russian Cyrillic is the Polivanov system, and for the Ukrainian is the Kovalenko system. As you told me in #14, the Ukrainian has 6 systems (Dibrova-Odynets, Fedorishin, Bondarenko, Nakazawa, Ruble, Kovalenko).

I have not found so much information for the Russian. Could the Polivanov and Kovalenko systems be enough, or are the others used as well?

**Comment by mks-h** [comment]
From my experience - I hear different variants in anime dubs, so all of them should be used. For example "Shinji" can be called "Сіндзі", "Шінджі" "Шинджі", etc. And yes, all of them sound different.

As for Russian - I know that "Shinji" can be called "Синдзи" and "Шынджи", IIRC, maybe there are more options.

On realkana.com you can use "Si" instead of "Shi", because, I guess, there is different romanization methods, too.

**Comment by mks-h** [comment]
Places that still needs translation:

- [x] On initial screen - Hiragana and Katakana buttons titles
- [x] On popup for choosing kana set - titles
- [x] Installed app title doesn't translate

I think, it might be good to firstly add those ^ things, then update translations, and set tag to latest.

**Comment by aeri** [comment]
> 
> 
> Places that still needs translation:
> 
>     * [X]  On initial screen - Hiragana and Katakana buttons titles
>     * [X]  On popup for choosing kana set - titles
>     * [X]  Installed app title doesn't translate
> 

Regarding these translations I have created a PR (#23) that solves these points, I don't link it so as not to close the Issue without solving the main issue.

Regarding the Cyrillization of the answers, I am looking for the best way to adapt the core it to also include Kanjis, I will surely use the JSON format to link question and possible answers.

**Comment by mks-h** [comment]
> I have created a PR (#23) that solves these points

Thanks!

> I will surely use the JSON format to link question and possible answers

Sounds good.

**Comment by aeri** [comment]
I have deployed a new release that supports Cyrillic script input for Ukrainian and Russian, sorry for the delay but it is finally implemented, could you please let me know if it works well?

**Comment by mks-h** [comment]
Sure! Good timing, I've just started using your app again

**Comment by mks-h** [comment]
It certainly works, but I would change the input text. I'll think about it and make a PR

**Comment by aeri** [comment]
Thanks for testing it, I look forward to your PR.
