### ISSUE TITLE
System's "go back" action leads to exiting app

### ISSUE THREAD

**Issue by mks-h** [aeri/Nihonoari-App#22]
Going back from training screen leads app to closing. After closing - it still is in "recent" menu, but when you open - it relaunches app.
I think, it should return to initial screen with previously selected kana's. Also, it should have "press back again to close app" confirmation.

**Comment by mks-h** [comment]
Afterthought - confirmation isn't really needed, as now it remembers chosen sets. Still good to have, tho

**Comment by aeri** [comment]
I have incorporated this functionality in the linked PR, the translations for Cyrillic languages have been done automatically, if you can take a look because I don't know how well they have been translated.

**Comment by mks-h** [comment]
> how well they have been translated.

Not well ;-) See my comment in PR
