### ISSUE TITLE
Enter Hiragana & Katakana looking at Romaji 

### ISSUE THREAD

**Issue by uunnxx** [aeri/Nihonoari-App#26]
Can we have an inverse like this ?

| look at  | type |
| ---- | ---- |
| a |あ|
| i | い|
| u | う|
| e | え|
| o | お|

Enter hiragana or katakana looking at / reading Romaji ?
Same functionality but inversed.

**Comment by uunnxx** [comment]
I have recommended nihonoari to several of my acquaintances, and they say it would be better to have a reverse.. and they are asking for similar app with romaji -> hiragana/katakana

**Comment by aeri** [comment]
Hey, thank you for the suggestion. I find this functionality very interesting and I will see how I can implement it in a user-friendly way :)

**Comment by aeri** [comment]
I have been working on the development of this feature (sorry for the delay) and I have noticed that the keyboards do not have a katakana input. The Katakana suggestion appears once Hiragana is entered but it cannot be entered directly. 

The implemented functionality covers both Hiragana and Katakana cases but it is still meaningless to enter Katakana.

**Comment by uunnxx** [comment]
I got you!
