### ISSUE TITLE
Hi! i would like to ask a few questions about the license...

### ISSUE THREAD

**Issue by cyan-2048** [aeri/Nihonoari-App#27]
I have made an exact clone of this app, and would like to know if it's okay with using the icons and name of the app, that's all thank you....

**Comment by aeri** [comment]
Hi, I saw it the other day by chance and I thought it was a very cool project. I'm glad you liked it and that you developed a version for KaiOS. Remember that the license I have set is **GPLv3** so if you have reused code you have to set it also as GPL and not as MIT as well as reference the original project/code.

I'm fine with you using the name and design of the original Nihonoari and thanks for the heads up ;)

**Comment by cyan-2048** [comment]
I have only used the icons and no code was used from the original app, so i am guessing I don't need to set is as GPL... I have also added reference to the original project, thank you very much for the quick response...
