### ISSUE TITLE
light mode

### ISSUE THREAD

**Issue by qupufu** [aeri/Nihonoari-App#31]
It would be nice if you could switch between light and dark mode either in app or by checking the system theme

**Comment by aeri** [comment]
Thanks for the suggestion, I chose the color palette because I liked the feeling of red combined with black, I have thought about using a black for AMOLED screens but I do not like the result so much.

I would not like to add many more options to the main menu so it may be interesting to be based on the theme of the system.

We will have to look at a color palette that looks nice for the light mode.

**Comment by xmha97** [comment]
Any update for this feature?

**Comment by aeri** [comment]
> Any update for this feature?

Hi, it is precisely the next functionality that I want to work on and develop, I will keep the current theme and color palette as a default but there will be an option to switch to a clear mode.

**Comment by xmha97** [comment]
> > Any update for this feature?
> 
> Hi, it is precisely the next functionality that I want to work on and develop, I will keep the current theme and color palette as a default but there will be an option to switch to a clear mode.

Thanks 🙏

Why? In my opinion, like other apps, this app should follow the system default theme by default.

**Comment by aeri** [comment]
It would be easy to automatically adapt to the theme of the system but it is a matter of aesthetic decision. The theme of the app is designed in the current dark and red tone series, based on the [traditional colors of Japan](https://en.wikipedia.org/wiki/Traditional_colors_of_Japan), I prefer to keep the user experience that provides this aesthetic as a differentiating style of the app. I think that setting the theme according to the system would lose part of this essence of the application.

However, I am interested in the proposal to include an optional light mode if users are more comfortable with a clearer, more natural and readable visual experience that light mode can provide.

**Comment by xmha97** [comment]
Ok, thanks 🙏
