### ISSUE TITLE
Impossible to distinguish `zu` and `ji` in reverse mode

### ISSUE THREAD

**Issue by pvrs12** [aeri/Nihonoari-App#33]
When in reverse mode `zu` and `ji` each have 2 different Kana translations, but the app only accepts one with no indication of which.

I think it should either accept either option (a) or show the Kana that the romaji is derived from (b). Elaborated below

a) `zu` accepts `ず` and `づ` and `ji` accepts `じ` and `ぢ`
b) When `zu` is displayed it also says `su` or `tsu` and when `ji` is displayed it also says `chi` or `shi`

**Comment by pvrs12** [comment]
Managed to capture some screenshots

Character entered:
![Screenshot_20220112-184743.png](https://user-images.githubusercontent.com/6956401/149240956-782d1db7-a617-465d-98b4-ad45bfdbba98.png)

Result:
![Screenshot_20220112-184746.png](https://user-images.githubusercontent.com/6956401/149240960-c347cfad-98f6-4ace-b03f-d18e359fe5bf.png)

**Comment by aeri** [comment]
It is true, thanks for the notice, I will look for a way to solve it.

**Comment by aeri** [comment]
Thanks for the PR, I haven't had time these days and was going to get around to it this week but I'm glad you took care of it.

**Comment by pvrs12** [comment]
No worries! Happy to help out
