### ISSUE TITLE
Scale the text for smaller displays

### ISSUE THREAD

**Issue by svin24** [aeri/Nihonoari-App#38]
![Screenshot_20220223-005819.png](https://user-images.githubusercontent.com/51864332/155233894-f6c2c47d-affb-4d71-b5c0-acbb60f7ebea.png)

As you can see the characters are partially hidden

**Comment by aeri** [comment]
Thanks for the heads up, what is your screen resolution? According to the screenshot you posted it is 1920x1080 which is the same resolution I have.

Could it be due to some zoom setting of the device? Anyway I will look for a way to make the text adaptive regardless of any factor.

**Comment by svin24** [comment]
no its probably because of the device PPI
It is an Xperia X https://www.calculatorsoup.com/calculators/technology/ppi-calculator.php?b=1080&a=1920&d=5&units_length=inch&action=solve

**Comment by aeri** [comment]
I have created a PR that should fix the issue of different resolution screens, I have used two other mobiles to check that it now looks fine.

So far I had not detected or been notified of this problem before, however, it seems to be a common problem on many devices.

**Comment by aeri** [comment]
I have deployed a new version with the changes that fix the adaptive screen size.
