### ISSUE TITLE
Ability To Choose A Set

### ISSUE THREAD

**Issue by seniorm0ment** [aeri/Nihonoari-App#4]
Please add ability to set specific groups to show of hiragana or katakana, so users can learn easily stuff they don't know, only needing to focus on a certain amount at a time.

**Comment by aeri** [comment]
I'm interested in the functionality, which grouping do you propose exactly?

**Comment by seniorm0ment** [comment]
> 
> 
>which grouping do you propose exactly?

essentially, one would be able to select which "groups" of hiragana they want (any similar for katakana).
For example:
select hiragana ka ki ku ke ko
then when you finish with that, you can deselect the k's and go on sa shi su se so, then they can add back the k's alongside the s's. so it's ka ki ku ke ko sa shi su se so.

Look at this for a clearer example (under "show/hide options)
https://itazuraneko.neocities.org/learn/kana.html

**Comment by aeri** [comment]
Okay, I understand, thank you for the suggestion, I will see how to implement it to make it as simple as possible. I want a very minimalist menu and I want it to be very easy.

**Comment by erihe251** [comment]
Another idea might be to only add new symbols into to set when the success rate over the last X tries is above a certain threshold. 

But this might be complicating things too much, I sympathize with your ambition to keep things simple!

**Comment by seniorm0ment** [comment]
I understand where you're going with that, personally though I don't see the major point. The user could just add the new set on when they feel personally comfortable. It'd be the least bloated way to do it imo and allow users to move on exactly when they feel right.

**Comment by seniorm0ment** [comment]
Any luck with this curiously?

**Comment by aeri** [comment]
I'll try to implement it in the next few days, sorry for the delay.

**Comment by aeri** [comment]
I have published a new release, you will tell me what you think about the result :)

**Comment by seniorm0ment** [comment]
Will check it out when fdroid publishes, thank you

**Comment by seniorm0ment** [comment]
@aeri How long does F-Droid take to build? Isn't it only a few days? It's been a week and hasn't been push to F-Droid?

**Comment by aeri** [comment]
That's what I think, plus the update is supposed to be automatic as soon as it finds a new release. It's just that I've never uploaded an update to F-Droid.

I'm going to change the fastlane and release a new one and see if they detect it out there. If it's not updated in a few days, I'll open an issue in Gitlab.

**Comment by aeri** [comment]
A week ago i started a [issue](https://gitlab.com/fdroid/fdroiddata/-/issues/2094) in F-Droid Gitlab to update the App, but I'm not getting much help. Maybe it's a matter of waiting for something else but it gives me the feeling that something is wrong. F-Droid is very "*complex*".

**Comment by seniorm0ment** [comment]
I'm not an app dev so I have not had to deal with any of this, but I believe a lot of devs somehow autopublish to F-Droid, then after a week F-Droid reviews it then builds it.
@IzzySoft may be able to provide some support on it, I actively see him communicating within F-Droid projects around Github. I believe he is the host of the IzzySoft repo on F-Droid so it makes sense.

**Comment by IzzySoft** [comment]
@grravity I'm not an app dev either. I've checked metadata against our reports, and left a comment pinging some of our packagers to investigate my findings. Should they confirm my suspicion, I'd've learned a new lesson for my task at maintaining metadata as well (when checking against `pubspec.yaml`, never to use `AutoUpdateMode: Tags` but always set it to `HTTP` – which for devs would mean to not increase the versions in `pubspec.yaml` before the corresponding release is ready).

Let's see what the packagers respond.
