### ISSUE TITLE
Introduce Spaced Repetition Mechanism

### ISSUE THREAD

**Issue by marcoXbresciani** [aeri/Nihonoari-App#5]
Spaced repetition mechanism (https://en.wikipedia.org/wiki/Spaced_repetition) could help improve memorizing kana.
There is also an interesting reply on Quora, on about how to repeat words/things to remember: https://www.quora.com/Whats-the-best-spaced-repetition-schedule
And I bet there already are available good and tested repetition algorithms such as those for Anki or Mnemosyne or so.

Give it a try.

**Comment by aeri** [comment]
Thank you for the suggestion to help improve the project :) I will look into how to implement it.

**Comment by aeri** [comment]
I am trying to implement a system some similar to [Leitner system](https://en.wikipedia.org/wiki/Leitner_system), however given the character of the app I do not see the possibility of working with daily objectives, but per session. That is to say, to establish a mechanism of spaced repetition per session, which is restarted when starting it again.

In this way the failed kanas will be repeated until they are correct.

**Comment by aeri** [comment]
I have published a new release in which I have implemented a spaced repetition algorithm per session, you will tell me what you think :)

**Comment by marcoXbresciani** [comment]
Cool. Still see 1.3.0 on FDroid, but it'll surely arrive.

**Comment by marcoXbresciani** [comment]
Got 1.4.0 from F-Droid. I've selected whole katakana and hiragana.
I've played a bit of kanas then I've mistyped a few off them on purpose, but after a while, still in the same session, I saw no repetition of those I've mistyped.

**Comment by marcoXbresciani** [comment]
Using only hiragana a, I, u, e, o and n, and mistipying one of them on purpose, the repetition seems more obvious.

**Comment by aeri** [comment]
The algorithm I have implemented works as follows:

There are 3 boxes of questions, in the first one (QUIZ) there is the whole selection of Kanas selected at the beginning, when one is asked, if it is correct it goes to the second box (PASSED) and if it fails it goes to the third box (FAILED).

```
             FAILED KANA
    +-------------------------+
    |                         |
    |                         |
    |                         v
+---+--+     +------+     +------+
|      |     |      |     |      |
| QUIZ |     |PASSED|     |FAILED|
|      |     |      |     |      |
+---+--+     +---+--+     +------+
    |            ^
    |            |
    |            |
    +------------+
      PASSED KANA
```
Once all the questions in the first box are exhausted, all the questions in the third box (FAILED) are moved to the first box to be asked again.
```
     +---+--+     +------+     +------+
     |      |     |      |     |      |
+--->+ QUIZ |     |PASSED|     |FAILED|
|    |      |     |      |     |      |
|    +---+--+     +---+--+     +--+---+
|                                 |
|                                 |
+---------------------------------+
```

This cycle is repeated until you get them all right and there is no kana in the third box, so all the kana in the second box will be moved to the first box to start over.

The spaced repetition implemented consists of not repeating a kana that you have already succeeded in until you have succeeded in all the others and mainly those that you have failed; in this way it favors the learning of the most failed ones.
